In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv("matches.csv")
df.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi
2,3,2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan
3,4,2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin
4,5,2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN

In [3]:
df.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2'],
      dtype='object')

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.isnull().sum()

id                 0
season             0
city               7
date               0
team1              0
team2              0
toss_winner        0
toss_decision      0
result             0
dl_applied         0
winner             3
win_by_runs        0
win_by_wickets     0
player_of_match    3
venue              0
umpire1            1
umpire2            1
dtype: int64

In [6]:
unique_teams=np.unique(np.append(df.team1.unique(),df.team2.unique()))

In [7]:
unique_teams

array(['Chennai Super Kings', 'Deccan Chargers', 'Delhi Daredevils',
       'Gujarat Lions', 'Kings XI Punjab', 'Kochi Tuskers Kerala',
       'Kolkata Knight Riders', 'Mumbai Indians', 'Pune Warriors',
       'Rajasthan Royals', 'Rising Pune Supergiant',
       'Rising Pune Supergiants', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad'], dtype=object)

In [8]:
df=df.dropna(inplace=True)

In [ ]:
df.shape

(625, 17)

In [ ]:
df.head(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi

In [ ]:
team1="Mumbai Indians"
team2="Rising Pune Supergiant"
matches=df[((df['team1']=="Mumbai Indians") & (df['team2']=="Rising Pune Supergiant")) | ((df['team2']=="Mumbai Indians") & (df['team1']=="Rising Pune Supergiant")) ]
total_matches=matches.shape[0]


win_team1=matches[matches['winner']==team1]
win_team2=matches[matches['winner']==team2]
draw=total_matches-(win_team1.shape[0]+win_team2.shape[0])
seasons=matches["season"]

In [ ]:
().sum()

np.int64(7)

In [ ]:
df[df['team2']=="Kochi Tuskers Kerala"]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
246,247,2011,Mumbai,15-04-2011,Mumbai Indians,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,normal,0,Kochi Tuskers Kerala,0,8,BB McCullum,Wankhede Stadium,BR Doctrove,PR Reiffel
251,252,2011,Kochi,18-04-2011,Chennai Super Kings,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,normal,1,Kochi Tuskers Kerala,0,7,BB McCullum,Nehru Stadium,K Hariharan,AL Hill
264,265,2011,Kochi,27-04-2011,Deccan Chargers,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,normal,0,Deccan Chargers,55,0,I Sharma,Nehru Stadium,HDPK Dharmasena,AL Hill
268,269,2011,Kochi,30-04-2011,Delhi Daredevils,Kochi Tuskers Kerala,Delhi Daredevils,bat,normal,0,Delhi Daredevils,38,0,V Sehwag,Nehru Stadium,HDPK Dharmasena,AL Hill
273,274,2011,Delhi,02-05-2011,Delhi Daredevils,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,normal,0,Kochi Tuskers Kerala,0,7,P Parameswaran,Feroz Shah Kotla,Asad Rauf,SL Shastri
293,294,2011,Indore,15-05-2011,Rajasthan Royals,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,normal,0,Kochi Tuskers Kerala,0,8,BJ Hodge,Holkar Cricket Stadium,PR Reiffel,RJ Tucker
296,297,2011,Chennai,18-05-2011,Chennai Super Kings,Kochi Tuskers Kerala,Chennai Super Kings,bat,normal,0,Chennai Super Kings,11,0,WP Saha,"MA Chidambaram Stadium, Chepauk",HDPK Dharmasena,RE Koertzen

In [11]:
matches=pd.read_csv("matches.csv")
balls=pd.read_csv("balls.csv")

In [13]:
matches.head(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong
1,2,2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi

In [16]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    object
 3   date             636 non-null    object
 4   team1            636 non-null    object
 5   team2            636 non-null    object
 6   toss_winner      636 non-null    object
 7   toss_decision    636 non-null    object
 8   result           636 non-null    object
 9   dl_applied       636 non-null    int64
 10  winner           633 non-null    object
 11  win_by_runs      636 non-null    int64
 12  win_by_wickets   636 non-null    int64
 13  player_of_match  633 non-null    object
 14  venue            636 non-null    object
 15  umpire1          635 non-null    object
 16  umpire2          635 non-null    object
dtypes: int64(5), object(12)
memory usage: 84.6+ KB

In [28]:
matches["id"]=matches["id"].astype('int8')
matches['dl_applied']=matches['dl_applied'].astype('int8')
matches['win_by_runs']=matches['win_by_runs'].astype('int8')
matches['win_by_wickets']=matches['win_by_wickets'].astype('int16')

In [30]:
matches.to_csv("new_matches.csv")

In [15]:
balls.head(2)

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals

In [31]:
balls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225954 entries, 0 to 225953
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ID                 225954 non-null  int64
 1   innings            225954 non-null  int64
 2   overs              225954 non-null  int64
 3   ballnumber         225954 non-null  int64
 4   batter             225954 non-null  object
 5   bowler             225954 non-null  object
 6   non-striker        225954 non-null  object
 7   extra_type         12049 non-null   object
 8   batsman_run        225954 non-null  int64
 9   extras_run         225954 non-null  int64
 10  total_run          225954 non-null  int64
 11  non_boundary       225954 non-null  int64
 12  isWicketDelivery   225954 non-null  int64
 13  player_out         11151 non-null   object
 14  kind               11151 non-null   object
 15  fielders_involved  7988 non-null    object
 16  BattingTeam        225954 non-null  object
dtypes: int64(9), object(8)
memory usage: 29.3+ MB

In [53]:
balls["ID"]=balls["ID"].astype("int32")
balls["innings"]=balls["innings"].astype("int8")
balls["overs"]=balls["overs"].astype("int8")
balls["ballnumber"]=balls["ballnumber"].astype("int8")
balls["batsman_run"]=balls["batsman_run"].astype("int8")
balls["total_run"]=balls["total_run"].astype("int8")
balls["extras_run"]=balls["extras_run"].astype("int8")
balls["non_boundary"]=balls["non_boundary"].astype("category")
balls["isWicketDelivery"]=balls["isWicketDelivery"].astype("category")
balls["extra_type"]=balls["extra_type"].astype("category")

In [54]:
balls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 225954 entries, 0 to 225953
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ID                 225954 non-null  int32
 1   innings            225954 non-null  int8
 2   overs              225954 non-null  int8
 3   ballnumber         225954 non-null  int8
 4   batter             225954 non-null  object
 5   bowler             225954 non-null  object
 6   non-striker        225954 non-null  object
 7   extra_type         12049 non-null   category
 8   batsman_run        225954 non-null  int8
 9   extras_run         225954 non-null  int8
 10  total_run          225954 non-null  int8
 11  non_boundary       225954 non-null  category
 12  isWicketDelivery   225954 non-null  category
 13  player_out         11151 non-null   object
 14  kind               11151 non-null   object
 15  fielders_involved  7988 non-null    object
 16  BattingTeam        225954 non-null  object
dtypes: category(3), int32(1), int8(6), object(7)
memory usage: 14.9+ MB

In [63]:
matches.sample(1)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
271,16,2011,Chennai,01-05-2011,Chennai Super Kings,Deccan Chargers,Chennai Super Kings,bat,normal,0,Chennai Super Kings,19,0,JA Morkel,"MA Chidambaram Stadium, Chepauk",Aleem Dar,RB Tiffin

In [64]:
matches.result.unique()

array(['normal', 'tie', 'no result'], dtype=object)

In [ ]:
matches[matches.result=='no result']

AttributeError: 'DataFrame' object has no attribute 'MatchNumber'